# Generated by Django 5.2.4 on 2025-08-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_department_user_group_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default='', max_length=100, verbose_name='User Code'),
        ),
    ]
