# Generated by Django 5.2.4 on 2025-08-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='user',
        ),
        migrations.DeleteModel(
            name='ForgetPassword',
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
