# Generated by Django 5.2.4 on 2025-08-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='department',
            field=models.ManyToManyField(to='organisation.department'),
        ),
        migrations.AddField(
            model_name='form',
            name='group',
            field=models.ManyToManyField(to='organisation.group'),
        ),
    ]
