# Generated by Django 5.2.4 on 2025-08-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_form_created_at_form_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='Enable'),
        ),
    ]
