# Generated by Django 5.2.4 on 2025-08-09 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_formquestions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormQuestions',
        ),
    ]
