# Generated by Django 5.2.4 on 2025-08-09 03:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_delete_formquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=2000, verbose_name='Question')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('answer_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('select', 'Select'), ('file', 'File')], default='text', max_length=30, verbose_name='Answer Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
