# Generated by Django 5.2.4 on 2025-08-09 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('form_index', models.IntegerField(default=0, verbose_name='Form Index')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.questions')),
            ],
        ),
    ]
