# Generated by Django 5.2.4 on 2025-08-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_formquestion_created_at_formquestion_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='file_type',
            field=models.CharField(default='none', max_length=50, verbose_name='File Type'),
        ),
        migrations.AddField(
            model_name='questions',
            name='max_len',
            field=models.IntegerField(default=10, verbose_name='Max Length'),
        ),
        migrations.AddField(
            model_name='questions',
            name='min_len',
            field=models.IntegerField(default=0, verbose_name='Min Length'),
        ),
        migrations.AddField(
            model_name='questions',
            name='options',
            field=models.TextField(default=1, verbose_name='Options seperated by ||'),
            preserve_default=False,
        ),
    ]
