# Generated by Django 5.2.4 on 2025-08-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_questions_file_type_questions_max_len_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='file_type',
            field=models.CharField(choices=[('none', 'None'), ('img', 'image/*'), ('pdf', 'pdf/*'), ('docx', 'doc/*'), ('csv', 'csv/*'), ('txt', 'txt/*')], default='none', max_length=50, verbose_name='File Type'),
        ),
    ]
