# Generated by Django 5.2.4 on 2025-08-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_alter_questions_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('select', 'Select'), ('file', 'File')], default='text', max_length=30, verbose_name='Answer Type'),
        ),
    ]
