# Generated by Django 5.2.4 on 2025-08-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_formuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='options',
            field=models.TextField(blank=True, null=True, verbose_name='Options seperated by ||'),
        ),
    ]
