# Generated by Django 5.2.4 on 2025-08-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_alter_questions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='file_type',
            field=models.CharField(choices=[('none', 'None'), ('image/*', 'Images (jpg, png, gif, etc.)'), ('application/pdf', 'PDF files'), ('application/msword', 'Word documents (.doc)'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'Word documents (.docx)'), ('text/csv', 'CSV files'), ('text/plain', 'Text files (.txt)'), ('application/vnd.ms-excel', 'Excel files (.xls)'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'Excel files (.xlsx)'), ('application/zip', 'ZIP archives'), ('*/*', 'All file types')], default='none', max_length=150, verbose_name='File Type'),
        ),
    ]
