# Generated by Django 5.2.4 on 2025-08-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_alter_questions_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='max_len',
            field=models.IntegerField(default=10, verbose_name='Max Length (characters for text, MB for files)'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='min_len',
            field=models.IntegerField(default=0, verbose_name='Min Length (characters for text, MB for files)'),
        ),
    ]
