# Generated by Django 5.2.4 on 2025-10-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_alter_questions_max_len_alter_questions_min_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_user_response', to='forms.form'),
        ),
    ]
