# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - AnomyForm

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/main_anomyform.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production-azure-flow
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt
      
      - name: Collect static files
        working-directory: ./backend
        run: |
          python manage.py collectstatic --noinput
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          ENVIRONMENT: production # Just for test
          COOKIE_DOMAIN: ${{ secrets.COOKIE_DOMAIN }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          DB_NAME: "dummy-name"
          DB_USER: "dummy-user"
          DB_PASSWORD: "dummy-password"
          DB_HOST: "dummy-host"
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            backend/
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_63C0E001D339421E87AAFDA6FBEDE6D3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_185DBD44E24247B08C0875F002F56FE6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EF747EAD6E724071B77AC2E9ACB93A84 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'AnomyForm'
          slot-name: 'Production'
          startup-command: 'bash startup.sh'
          